### ISSUE TITLE
Logging error at the end of benchmark 

### ISSUE THREAD

**Issue by ntraichel** [ovgu-FINken/multi_robot_path_planning#58]
When logging the results of the benchmark the following error rises: 
 ---> IOError: close() called during concurrent operation on the same file object

**Comment by ntraichel** [comment]
According to this question (https://stackoverflow.com/questions/29890603/ioerror-close-called-during-concurrent-operation-on-the-same-file-object) this is some issue with **threading.**

**Comment by bastinat0r** [comment]
So the main problem is that the logger is opening and closing files during `rospy.spin()` with a message-callback in `evaluation_controller.py`. The callback runs in a multi-threaded environment, but opening and closing files is not thread save.

I really see only two ways to resolve the problem: Either save the messages in a queue and handle the writing within the main thread (i.e. use rate.sleep() rather than rospy.spin() with timers) or publish the output on a message and have a single node that listens for that message and writes the file.
